# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23cb3e98b099576694f4470528ca3812b4a4397e1d46b3afb6de4977b25c27d448d4de9db9220cf83c14506a0e7386345ed278f395938bf5e0586b8c8f85d363

test:
  secret_key_base: 40f23dc132a4500cd55f9fc0c3cfc5a9efad73b94b67b5a86a4cd7a0a5027f18e648f08b24980591a66c435462bf315250d377d122c9b953fb44d05e2cfa5128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
